version: '3.8'

services:
  frontend:
    image: node:20-alpine
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:4000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    # Add healthcheck to ensure API is running
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 3 
