version: '3.8'

services:
  frontend:
    build:
      context: .
      target: builder  # Use the builder stage only
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - API_URL=http://api:4000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    command: npm run dev
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Enable polling for better hot reload in Docker
      - WATCHPACK_POLLING=true    # Enable polling for better file watching
    command: npm run dev
    # Add healthcheck to ensure API is running
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 3 
